apiVersion: v1
kind: ConfigMap

metadata:
  name: "inventory-app-config-frontend-{{ .Values.color }}"

data:
  backend_host: {{ .Values.backend_host | quote }}
  backend_port: {{ .Values.backend_port | quote }}