apiVersion: v1
kind: ConfigMap

metadata:
  name: inventory-app-config

data:
  DB_HOST: {{ .Values.db_host | quote }}
  DB_PORT: {{ .Values.db_port | quote }}
  FRONTEND_HOST: {{ .Values.frontend_host | quote }}
  FRONTEND_PORT: {{ .Values.frontend_port | quote }}