image:
  repository: rajatrulaniya/inventory-backend
  tag: "latest" ## overridden by CI/CD

replicaCount: 1

db_host: host.db.com ## overridden by CI/CD
db_port: "5432"

frontend_host: app.domain.com ## overridden by CI/CD
frontend_port: 3000 ## overridden by CI/CD

color: blue ## overridden by CI/CD
activeColor: blue ## overridden by CI/CD